name: noma_environment
channels:
  - conda-forge
  - pytorch
  - defaults
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
dependencies:
  # -------------------------- 移除 Windows 不存在的包：readline、ncurses、libuuid、libnsl --------------------------
  - asttokens=2.0.5
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bzip2=1.0.8
  - ca-certificates=2022.5.18.1
  - debugpy=1.6.0
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - ipykernel=6.13.0
  - ipython=8.4.0
  - jedi=0.18.1
  - jupyter_client=7.3.1
  - jupyter_core=4.10.0
  - libffi=3.4.2
  - libsodium=1.0.18  # 仅保留 Windows 有对应包的依赖
  - libzlib=1.2.12
  - matplotlib-inline=0.1.3
  - nest-asyncio=1.5.5
  - openssl=3.0.3
  - packaging=21.3
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.1.1
  - prompt-toolkit=3.0.29
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.12.0
  - python=3.9
  - python-dateutil=2.8.2
  - python_abi=3.9=2_cp39
  - pyzmq=23.0.0
  - setuptools=62.3.2  # 已删除 readline
  - six=1.16.0
  - sqlite=3.38.5
  - stack_data=0.2.0
  - tk=8.6.12
  - tornado=6.1
  - traitlets=5.2.1.post0
  - tzdata=2022a
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.12
  # -------------------------- pip 依赖不变（无需修改）--------------------------
  - pip:
    - absl-py==1.0.0
    - astunparse==1.6.3
    - attrs==21.4.0
    - brewer2mpl==1.4.1
    - cachetools==5.0.0
    - certifi==2021.10.8
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - chex==0.1.3
    - click==8.0.4
    - cloudpickle==2.0.0
    - coverage==6.3.2
    - cryptography==37.0.2
    - cycler==0.11.0
    - dill==0.3.5.1
    - distrax==0.1.2
    - dm-acme==0.4.0
    - dm-control==1.0.3.post1
    - dm-env==1.5
    - dm-haiku==0.0.6
    - dm-reverb-nightly
    - dm-sonnet==2.0.0
    - dm-tree==0.1.6
    - docopt==0.6.2
    - execnet==1.9.0
    - factories==1.2.0
    - flatbuffers==2.0
    - fonttools==4.33.3
    - gast==0.5.3
    - glfw==2.5.3
    - google-auth==2.6.2
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.45.0
    - gym==0.23.1
    - gym-notices==0.0.6
    - h5py==3.6.0
    - idna==3.3
    - importlab==0.7
    - importlib-metadata==4.11.3
    - iniconfig==1.1.1
    - jax==0.3.4
    - jaxlib==0.3.2
    - jmp==0.0.2
    - josepy==1.13.0
    - keras==2.8.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.2
    - labmaze==1.0.5
    - latexify-py==0.1.1
    - libclang==13.0.0
    - libcst==0.4.1
    - lxml==4.8.0
    - markdown==3.3.6
    - matplotlib==3.5.2
    - mock==4.0.3
    - mujoco==2.2.0
    - mypy-extensions==0.4.3
    - networkx==2.7.1
    - ninja==1.10.2.3
    - numpy==1.22.3
    - oauthlib==3.2.0
    - opt-einsum==3.3.0
    - optax==0.1.2
    - pandas==1.4.1
    - pillow==9.0.1
    - pipreqs==0.4.11
    - pluggy==1.0.0
    - portpicker==1.5.0
    - protobuf==3.20.0
    - psutil==5.9.0
    - py==1.11.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pygal==3.0.0
    - pyopengl==3.1.6
    - pyopenssl==22.0.0
    - pyparsing==2.4.7
    - pyrfc3339==1.1
    - pytest==7.1.1
    - pytest-cov==3.0.0
    - pytest-forked==1.4.0
    - pytest-sugar==0.9.4
    - pytest-xdist==2.5.0
    - pytype==2022.3.29
    - pytz==2022.1
    - pyyaml==6.0
    - qute==3.0.11
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - requests-toolbelt==0.9.1
    - rlax==0.1.2
    - rsa==4.8
    - scipy==1.8.0
    - scribble==1.0.0
    - svgwrite==1.4.2
    - tabulate==0.8.9
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.8.0
    - tensorflow-io-gcs-filesystem==0.24.0
    - tensorflow-probability==0.16.0
    - termcolor==1.1.0
    - tf-estimator-nightly==2.8.0.dev2021122109
    - toml==0.10.2
    - tomli==2.0.1
    - toolz==0.11.2
    - tqdm==4.64.0
    - tree==0.2.4
    - trfl==1.2.0
    - typing-extensions==4.1.1
    - typing-inspect==0.7.1
    - urllib3==1.26.9
    - werkzeug==2.0.3
    - wrapt==1.14.0
    - yarg==0.1.9
    - zipp==3.7.0